spring.application.name=nprrs-tagdog-backend

sistema.admin.email=admin@email.com
sistema.admin.senha=admin123

security.jwt.secret=mysupersecretkeymysupersecretkey123!
security.jwt.expiration=600

# Banco de dados Mysql
#springring.datasource.url=jdbc:mysql://localhost:3306/tagdog
#spring.datasource.username=root
#spring.datasource.password=senaisp
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false

#Banco de dados H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console