spring.application.name=nprrs-tagdog-backend

sistema.admin.email=admin@email.com
sistema.admin.senha=admin123

security.jwt.secret=mysupersecretkeymysupersecretkey123!
security.jwt.expiration=600

#Banco de dados Mysql
#springring.datasource.url=jdbc:mysql://localhost:3306/tagdog
#spring.datasource.username=root
#spring.datasource.password=senaisp
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false

#Banco de dados H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tag.dog.tcc@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Configuração do broker (exemplo local)
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=app-local
mqtt.username=
mqtt.password=

# Configurações adicionais
mqtt.clean-session=true
mqtt.automatic-reconnect=true
mqtt.keep-alive-interval=60
mqtt.connection-timeout=30
mqtt.default-qos=1

# Exemplo com SSL
# mqtt.broker-url=ssl://meu-broker:8883
# javax.net.ssl.trustStore=classpath:meu_truststore.jks
# javax.net.ssl.trustStorePassword=minhasenha
# javax.net.ssl.trustStoreType=JKS

# Mqtt no powershell
#mosquitto_pub -h localhost -t "0806meupet/rastreador/coordenadas" -m '{\"numero\": \"1\", \"latitude\": \"-23.591316433799992\", \"longitude\": \"-46.64509172099156\", \"dataCriado\": \"25/03/2026 10:00:00\"}'