spring.application.name=nprrs-tagdog-backend

# Banco de dados Mysql
#springring.datasource.url=jdbc:mysql://localhost:3306/tagdog
#spring.datasource.username=root
#spring.datasource.password=senaisp
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false